language: rust

env:
  global:
    - PROJECT_NAME=timeline

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

matrix:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin
      rust: stable
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
